services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine-slim
    restart: always
    networks:
      - net_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - var-lib-nginx:/var/lib/nginx
      # - ./bind/var-lib-nginx:/var/lib/nginx
      # -  etc-nginx-templates:/etc/nginx/templates
      # - ./bind/etc-nginx-templates:/etc/nginx/templates
      # - ./nginx-html:/usr/share/nginx/html

networks:
  net_nginx:
    external: true

volumes:
  var-lib-nginx:
    external: true
  etc-nginx-templates:
    external: true
