services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine-slim
    restart: always
    networks:
      - net_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - vol_nginx_data:/var/lib/nginx
      # - ./bind/var-lib-nginx:/var/lib/nginx
      # - ./templates:/etc/nginx/templates

networks:
  net_nginx:
    external: true

volumes:
  vol_nginx_data:
    external: true
